### ISSUE TITLE
Express router integration doesn't seem to work

### ISSUE THREAD

**Issue by ThomasBerne** [hidekatsu-izuno/h3-express#1]
When I define an express handler with an express router, it doesn't seem to work.

![image](https://user-images.githubusercontent.com/23033483/205225853-6365f5d0-d85c-49eb-87f0-1cc528beab4f.png)
![image](https://user-images.githubusercontent.com/23033483/205226060-6370b1d6-1237-4fd8-b1b8-251cf30238ad.png)

I didn't see code in this application taking care of it. Is it an abandonned feature?

**Comment by hidekatsu-izuno** [comment]
I understand this issue and have fixed this bug.
If you try the new version: v0.3.0. it will be resolved.
